source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

############ plugins ##################

plugin 'cocoapods-repo-svn', :sources => [
  'https://192.0.0.183/Control/TeleConference/trunk/components/iOS/Tool/HKPrivateSVNPods'
]

plugin 'cocoapods-art', :sources => [
  'Cocoa-proxy',
  'Cocoa-trans-local'
]

target 'ConfAppTs' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # 图标字体
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'HKCommonCmp', '1.0.1'

  target 'ConfAppTsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
